### ISSUE TITLE
3.0.0 removes trailing ,* wildcard definition from Import-Package definition

### ISSUE THREAD

**Issue by nzall** [ops4j/org.ops4j.pax.tinybundles#7]
First off, apologies for creating an issue on here instead of on your Jira installation as recommended. I tried to create an account (created a second even after the first didn't work), but it gives me the error that my account doesn't have access to your Jira on ops4j.jira.com.

I just upgraded our own tinybundles dependency from 1.0.0 to 3.0.0, and while it was a quite painless transition (just needed to fix 1 import), there is 1 change that I don't know how it's going to impact me: the latest version removes the trailing `,*` wildcard package import definition from the Import-Package definition we pass along to the package:

```
private static final String IMPORT_PACKAGES_SCRIPTING_PHASE = "phases.scripting.impl,phases.spi,*";


         bundle.set(Constants.IMPORT_PACKAGE , IMPORT_PACKAGES_SCRIPTING_PHASE);
        // create the bundle as an inputstream with tinybundles and bnd
        InputStream outputBundleJarInputStream = bundle.build(withBnd());
```
        
This results in a bundle with the Import-Package declaration in the MANIFEST.MF file simply being `phases.scripting.impl,phases.spi`, completely removing the `,*` wildcard package definition at the end. The main concern I have is whether this might be done in error, because I don't know if this wildcard definition might sometimes be necessary.

**Comment by laeubi** [comment]
A "wildcard" is not valid for import package, since there is no such thing in the OSGi-Spec. BND-Tooling allows to specify a "Wildcard" so compute the required import packages on build-time and replace it with the needed packages then.
