### ISSUE TITLE
Support resource filters [PAXTB-1]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.tinybundles#9]
**[Toni Menzel](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:e7e50a9b-1dd6-45df-b446-7b0e65306e2b)** created **[PAXTB-1](https://ops4j1.jira.com/browse/PAXTB-1)** 

so, instead of adding resources one by one, it would be good to have some kind of "*" placeholder support.<br /> Though, this will turn "load by classloader" to "load by filesystem" killing benefits (resource location independence) .

---

Votes: 0, Watches: 1

---
**Referenced issues**

**relates to:**
* #15 - Adding a class (TinyBundle#add(..)) with inner classes is not recursive [PAXTB-6]
* #11 - Adding inner classes to bundle [PAXTB-3]

**Comment by oliverlietz** [comment]
`ClassFinder` supports multiple protocols and patterns to add classes.
